In [1]:
import numpy as np
import time
'''
Problems:
0) How many dimensions are there in b
1)Tell the shape of b
2) Extract from b the 2 and 3rd row, and last 2 innermost elements
3) Extract from b the 2 and 3rd col and 1st 2 innermost elements
'''
b =   [
           [
               [1,2,3,4,5],
                [11,22,33,44,55],
                [111,222,333,444,555]
            ],
            [
            [100,200,300,400,500],
            [1000,2000,3000,4000,5000],
            [20,30,40,50,60]
            ],
            [
              [7,8,9,10,11],
            [77,88,99,100,1100],
            [101,201,301,401,501]
            ],
            [
                [71, 81, 91, 101, 111],
                [771, 881, 991, 1001, 11001],
                [1011, 2011, 3011, 401, 5011]
            ]
    ]
b_arr = np.array(b)
print ("b_arr.shape", b_arr.shape)
t1 = time.time()
print ("b_arr[0]", b_arr[0])
print ("b_arr[1]", b_arr[1])
print ("b_arr[2]", b_arr[2])
print ("b_arr[0][0]", b_arr[0][0])
print ("b_arr[0][1]", b_arr[0][1])
print ("b_arr[0][2]", b_arr[0][2])
print ("b_arr[0][1][0]", b_arr[0][1][0])
print ("b_arr[0][1][1]", b_arr[0][1][1])
print ("b_arr[0:2,0:2,0:2]",b_arr[0:2,0:2,0:2])
t2 = time.time()
print ("time taken =", t2-t1)
print ("b_arr[0:2,0:2,1:3]",b_arr[0:2,0:2,1:3], "shape of b_arr=", b_arr.shape)


b_arr.shape (4, 3, 5)
b_arr[0] [[  1   2   3   4   5]
 [ 11  22  33  44  55]
 [111 222 333 444 555]]
b_arr[1] [[ 100  200  300  400  500]
 [1000 2000 3000 4000 5000]
 [  20   30   40   50   60]]
b_arr[2] [[   7    8    9   10   11]
 [  77   88   99  100 1100]
 [ 101  201  301  401  501]]
b_arr[0][0] [1 2 3 4 5]
b_arr[0][1] [11 22 33 44 55]
b_arr[0][2] [111 222 333 444 555]
b_arr[0][1][0] 11
b_arr[0][1][1] 22
b_arr[0:2,0:2,0:2] [[[   1    2]
  [  11   22]]

 [[ 100  200]
  [1000 2000]]]
time taken = 0.0019600391387939453
b_arr[0:2,0:2,1:3] [[[   2    3]
  [  22   33]]

 [[ 200  300]
  [2000 3000]]] shape of b_arr= (4, 3, 5)
