In [ ]:
import numpy as np

In [1]:
""""
This will explain the axis concept in python esp numpy
I have broken the 3, 4, 5 shape and calculated manually as per the axis to give you a clear idea on how axis works
"""""
import numpy as np
# b = np.array ([[0,1], [2,5]])
# print ("b[0, :]", b[0, :])
# print ("b[1, :]", b[1, :])
# print ("b[0, :] + b[1, :]=",   b[0, :] + b[1, :], b.sum(axis = 0)) #[2, 6]
# print ("b[: 0]", b[ :, 0])
# print ("b[ :, 1])= ", b[ :, 1])
# print ("b[ :, 0] + b[ :, 1]=",   b[ :, 0] + b[ :, 1], b.sum(axis = 1)) #[1, 7]
#
a = np.array(
    [
    [[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [7, 8,9, 10, 11], [-1, -2, -3, -4, -5]],
    [[20, 21, 22, 23, 24], [22,23,24, 25, 26], [25, 26, 27, 28, 29], [-20, -21, -22, -23, -24]],
    [[40, 41, 42, 43, 44], [43, 44, 45, 46, 47], [46, 47, 48, 49, 50], [-40, -41, -42, -43, -44]]
    ]
)
print (a.shape)
print ("a = ", a)
#iterating:
for i in a:
    print ("i= ", i)
#slicing:
print ("a[:, 2:4, :]", a[:, 2:4, :])
print ("a[:, 2:4, 1:3]", a[:, 2:4, 1:3])

axis = 0
b =  np.sum(a, axis = axis)
c = a [0, :, : ] + a [ 1, :, :] + a [2,:,:] # THis is the meaning of axis 0
print ("c == np.sum(a, axis = axis)", axis, c == b)
print ("np.sum(a, axis = 0)", b, b.shape)
print ("np.sum(a, axis = 0) == a", b == a.sum(axis = axis))

axis = 1
c = a [:, 0, : ] + a [ :, 1, :] + a [:,2,:] + a [:,3,:]# THis is the meaning of axis 1
b =  np.sum(a, axis = axis)
print ("c == np.sum(a, axis = axis)", c == b)
print ("axis = ,",  axis, "np.sum(a, axis = 1) == a", b == a.sum(axis = axis))

axis = 2
b =  np.sum(a, axis = axis)
c = a[:, :, 0 ] + a [ :, :, 1] + a [:, :, 2] + a [:, :, 3] + a [:, :, 4] # THis is the meaning of axis 2
print ("np.sum(a, axis = 2)", b, "c==b", c==b)
print ("np.sum(a, axis = 2) == a", b ==a.sum(axis = axis))

axis = -1
print ("np.sum(a, axis = -1)", np.sum(a))
print ("np.sum(a, axis = -1)==a", np.sum(a) == a.sum(), a.sum())

a= np.array([[0, 0, 0],
       [0, 1, 0],
       [0, 2, 0],
       [1, 0, 0],
       [1, 1, 0]])
b = a[0,:] + a[1,:] + a[2,:]+a[3,:] + a[4, :]
print("sum(axis=0)", np.sum(a, axis=0))
print ("b)=", b)

b =a[:, 0]+a[:, 1]+a[:,2]
print("sum(axis=1)", np.sum(a, axis=1, keepdims = False))
print("sum(axis=1)", np.sum(a, axis=1, keepdims = True))
print ("b)=", b)
print (np.sum((np.sum(a, axis=1)==b), keepdims=False))



(3, 4, 5)
a =  [[[  1   2   3   4   5]
  [  4   5   6   7   8]
  [  7   8   9  10  11]
  [ -1  -2  -3  -4  -5]]

 [[ 20  21  22  23  24]
  [ 22  23  24  25  26]
  [ 25  26  27  28  29]
  [-20 -21 -22 -23 -24]]

 [[ 40  41  42  43  44]
  [ 43  44  45  46  47]
  [ 46  47  48  49  50]
  [-40 -41 -42 -43 -44]]]
i=  [[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [-1 -2 -3 -4 -5]]
i=  [[ 20  21  22  23  24]
 [ 22  23  24  25  26]
 [ 25  26  27  28  29]
 [-20 -21 -22 -23 -24]]
i=  [[ 40  41  42  43  44]
 [ 43  44  45  46  47]
 [ 46  47  48  49  50]
 [-40 -41 -42 -43 -44]]
a[:, 2:4, :] [[[  7   8   9  10  11]
  [ -1  -2  -3  -4  -5]]

 [[ 25  26  27  28  29]
  [-20 -21 -22 -23 -24]]

 [[ 46  47  48  49  50]
  [-40 -41 -42 -43 -44]]]
a[:, 2:4, 1:3] [[[  8   9]
  [ -2  -3]]

 [[ 26  27]
  [-21 -22]]

 [[ 47  48]
  [-41 -42]]]
c == np.sum(a, axis = axis) 0 [[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
n